apiVersion: v1
data:
  SLACK_APP_TOKEN: 
  SLACK_BOT_TOKEN: 
  GOOGLE_API_KEY: 
  AGENT_MODEL: 
  AGENT_APP_NAME: 
  AGENT_NAME: 
kind: Secret
metadata:
  name: sladk-secrets
  namespace: sladk
type: Opaque

